const fs = require('fs');
const path = require('path');
const { readTemplate, writeFile, execOptional } = require('../shared/utils');
const { resolveKeys } = require('../shared/keys');

function tomlString(value) {
  return JSON.stringify(value || '');
}

function renderCodexConfig({ githubToken = '', context7Key = '', tavilyKey = '' } = {}) {
  return `# Generated by vibe-setup --codex

[agents]
max_threads = 6
max_depth = 1

[mcp_servers.github]
command = "npx"
args = [
    "-y",
    "@modelcontextprotocol/server-github",
]

[mcp_servers.github.env]
GITHUB_PERSONAL_ACCESS_TOKEN = ${tomlString(githubToken)}

[mcp_servers.postgres]
command = "npx"
args = [
    "-y",
    "@modelcontextprotocol/server-postgres",
    "postgresql://localhost:5432/postgres",
]

[mcp_servers.puppeteer]
command = "npx"
args = [
    "-y",
    "@modelcontextprotocol/server-puppeteer",
]

[mcp_servers.sequential-thinking]
command = "npx"
args = [
    "-y",
    "@modelcontextprotocol/server-sequential-thinking",
]

[mcp_servers.context7]
command = "npx"
args = [
    "-y",
    "@upstash/context7-mcp",
    "--api-key",
    ${tomlString(context7Key)},
]

[mcp_servers.tavily]
command = "npx"
args = [
    "-y",
    "tavily-mcp",
]

[mcp_servers.tavily.env]
TAVILY_API_KEY = ${tomlString(tavilyKey)}

[mcp_servers.qmd]
command = "qmd"
args = [
    "mcp",
]
`;
}

function parseMarkdownAgent(content, sourceName) {
  const match = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) throw new Error(`${sourceName} is missing frontmatter`);

  const meta = {};
  for (const line of match[1].split('\n')) {
    const idx = line.indexOf(':');
    if (idx === -1) continue;
    meta[line.slice(0, idx).trim()] = line.slice(idx + 1).trim();
  }

  if (!meta.name) throw new Error(`${sourceName} is missing a name`);
  return { meta, body: match[2].trim() };
}

function tomlLongString(value) {
  return `'''\n${value.replace(/'''/g, "'\\''")}\n'''`;
}

function renderAgentToml(fileName, content) {
  const { meta, body } = parseMarkdownAgent(content, fileName);
  const sourceNote = `<source>
Ported from general-plugin/agents/${fileName}. Keep that Claude Code source file unchanged.
</source>

`;
  const toolNote = meta.tools
    ? `\n\n<codex_tool_guidance>\nOriginal Claude Code tool guidance: ${meta.tools}. In Codex, use the tools available in the current session and follow the same intent. If this agent is review-only, do not modify files.\n</codex_tool_guidance>`
    : '';

  return [
    `name = ${tomlString(meta.name)}`,
    `description = ${tomlString(meta.description || `${meta.name} subagent`)}`,
    `developer_instructions = ${tomlLongString(sourceNote + body + toolNote)}`,
    '',
  ].join('\n');
}

function writeCodexAgents(cwd) {
  const agentsSrc = path.join(__dirname, '..', 'general-plugin', 'agents');
  const agentsDest = path.join(cwd, '.codex', 'agents');
  if (!fs.existsSync(agentsSrc)) return;

  fs.mkdirSync(agentsDest, { recursive: true });
  for (const file of fs.readdirSync(agentsSrc)) {
    if (!file.endsWith('.md')) continue;
    const source = fs.readFileSync(path.join(agentsSrc, file), 'utf8');
    const toml = renderAgentToml(file, source);
    const { meta } = parseMarkdownAgent(source, file);
    writeFile(path.join(agentsDest, `${meta.name}.toml`), toml);
  }
}

function writeLocalMarketplaceIfSourcesExist(cwd) {
  const generalPlugin = path.join(cwd, 'general-plugin');
  const obsidianPlugin = path.join(cwd, 'obsidian-plugin');
  if (!fs.existsSync(generalPlugin) || !fs.existsSync(obsidianPlugin)) return;

  const marketplace = {
    name: 'vibe-coding',
    interface: { displayName: 'Vibe Coding' },
    plugins: [
      {
        name: 'general-plugin',
        source: { source: 'local', path: '../../general-plugin' },
        policy: { installation: 'AVAILABLE', authentication: 'ON_INSTALL' },
        category: 'Productivity',
      },
      {
        name: 'obsidian-plugin',
        source: { source: 'local', path: '../../obsidian-plugin' },
        policy: { installation: 'AVAILABLE', authentication: 'ON_INSTALL' },
        category: 'Productivity',
      },
    ],
  };

  writeFile(
    path.join(cwd, '.agents', 'plugins', 'marketplace.json'),
    JSON.stringify(marketplace, null, 2) + '\n'
  );
}

async function setup(cwd, { yes = false, reconfigure = false } = {}) {
  console.log('[INFO] Configuring Codex...');

  // --- .vibe base ---
  const vibe = path.join(cwd, '.vibe');
  fs.mkdirSync(vibe, { recursive: true });

  // --- AGENTS.md ---
  writeFile(path.join(cwd, 'AGENTS.md'), readTemplate('global-claude.md'));

  // --- API keys ---
  const keys = await resolveKeys([
    { name: 'GITHUB_PERSONAL_ACCESS_TOKEN', hint: 'github.com/settings/tokens' },
    { name: 'CONTEXT7_API_KEY',             hint: 'context7.com' },
    { name: 'TAVILY_API_KEY',               hint: 'tavily.com' },
  ], { yes, reconfigure });

  // --- .codex/config.toml ---
  const codexDir = path.join(cwd, '.codex');
  fs.mkdirSync(codexDir, { recursive: true });
  const configPath = path.join(codexDir, 'config.toml');
  let writeConfig = true;
  if (fs.existsSync(configPath) && !yes) {
    const { default: inquirer } = await import('inquirer');
    const { override } = await inquirer.prompt([{
      type: 'confirm',
      name: 'override',
      message: '.codex/config.toml already exists. Override with latest vibe-setup config?',
      default: false,
    }]);
    writeConfig = override;
  }

  if (writeConfig) {
    writeFile(
      configPath,
      renderCodexConfig({
        githubToken: keys.GITHUB_PERSONAL_ACCESS_TOKEN || '',
        context7Key: keys.CONTEXT7_API_KEY || '',
        tavilyKey: keys.TAVILY_API_KEY || '',
      })
    );
  }

  // --- Subagents ---
  writeCodexAgents(cwd);

  // --- Repo-local marketplace metadata when running from this repository ---
  writeLocalMarketplaceIfSourcesExist(cwd);

  // --- Codex plugin update/install flow ---
  execOptional('codex plugin marketplace add AndrewChang-cpu/vibe-coding-configuration');
  execOptional('codex plugin marketplace upgrade vibe-coding');
  execOptional('codex plugin add general-plugin@vibe-coding');
  execOptional('codex plugin add obsidian-plugin@vibe-coding');

  console.log('[SUCCESS] Codex configured.');
}

module.exports = { setup };
