const fs = require('fs');
const os = require('os');
const path = require('path');
const { readTemplate, writeFile, exec } = require('../shared/utils');
const { resolveKeys } = require('../shared/keys');

const CODEX_CONFIG_SECTIONS = [
  'agents',
  'mcp_servers.github',
  'mcp_servers.github.env',
  'mcp_servers.postgres',
  'mcp_servers.puppeteer',
  'mcp_servers.sequential-thinking',
  'mcp_servers.context7',
  'mcp_servers.tavily',
  'mcp_servers.tavily.env',
  'mcp_servers.qmd',
];

function tomlString(value) {
  return JSON.stringify(value || '');
}

function renderCodexConfig({ githubToken = '', context7Key = '', tavilyKey = '' } = {}) {
  return `# Generated by vibe-setup --codex

[agents]
max_threads = 6
max_depth = 1

[mcp_servers.github]
command = "npx"
args = [
    "-y",
    "@modelcontextprotocol/server-github",
]

[mcp_servers.github.env]
GITHUB_PERSONAL_ACCESS_TOKEN = ${tomlString(githubToken)}

[mcp_servers.postgres]
command = "npx"
args = [
    "-y",
    "@modelcontextprotocol/server-postgres",
    "postgresql://localhost:5432/postgres",
]

[mcp_servers.puppeteer]
command = "npx"
args = [
    "-y",
    "@modelcontextprotocol/server-puppeteer",
]

[mcp_servers.sequential-thinking]
command = "npx"
args = [
    "-y",
    "@modelcontextprotocol/server-sequential-thinking",
]

[mcp_servers.context7]
command = "npx"
args = [
    "-y",
    "@upstash/context7-mcp",
    "--api-key",
    ${tomlString(context7Key)},
]

[mcp_servers.tavily]
command = "npx"
args = [
    "-y",
    "tavily-mcp",
]

[mcp_servers.tavily.env]
TAVILY_API_KEY = ${tomlString(tavilyKey)}

[mcp_servers.qmd]
command = "qmd"
args = [
    "mcp",
]
`;
}

function removeTomlSections(content, sectionNames) {
  const targets = new Set(sectionNames);
  const kept = [];
  let skipping = false;

  for (const line of content.split('\n')) {
    const match = line.match(/^\[([^\]]+)\]\s*$/);
    if (match) skipping = targets.has(match[1]);
    if (!skipping) kept.push(line);
  }

  return kept.join('\n').trimEnd();
}

function mergeCodexConfig(existing, generated) {
  const base = removeTomlSections(existing, CODEX_CONFIG_SECTIONS);
  return `${base ? `${base}\n\n` : ''}${generated.trimEnd()}\n`;
}

function parseMarkdownAgent(content, sourceName) {
  const match = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) throw new Error(`${sourceName} is missing frontmatter`);

  const meta = {};
  for (const line of match[1].split('\n')) {
    const idx = line.indexOf(':');
    if (idx === -1) continue;
    meta[line.slice(0, idx).trim()] = line.slice(idx + 1).trim();
  }

  if (!meta.name) throw new Error(`${sourceName} is missing a name`);
  return { meta, body: match[2].trim() };
}

function tomlLongString(value) {
  return `'''\n${value.replace(/'''/g, "'\\''")}\n'''`;
}

function renderAgentToml(fileName, content) {
  const { meta, body } = parseMarkdownAgent(content, fileName);
  const sourceNote = `<source>
Ported from general-plugin/agents/${fileName}. Keep that Claude Code source file unchanged.
</source>

`;
  const toolNote = meta.tools
    ? `\n\n<codex_tool_guidance>\nOriginal Claude Code tool guidance: ${meta.tools}. In Codex, use the tools available in the current session and follow the same intent. If this agent is review-only, do not modify files.\n</codex_tool_guidance>`
    : '';

  return [
    `name = ${tomlString(meta.name)}`,
    `description = ${tomlString(meta.description || `${meta.name} subagent`)}`,
    `developer_instructions = ${tomlLongString(sourceNote + body + toolNote)}`,
    '',
  ].join('\n');
}

function writeCodexAgents(codexDir) {
  const agentsSrc = path.join(__dirname, '..', 'general-plugin', 'agents');
  const agentsDest = path.join(codexDir, 'agents');
  if (!fs.existsSync(agentsSrc)) return;

  fs.mkdirSync(agentsDest, { recursive: true });
  for (const file of fs.readdirSync(agentsSrc)) {
    if (!file.endsWith('.md')) continue;
    const source = fs.readFileSync(path.join(agentsSrc, file), 'utf8');
    const toml = renderAgentToml(file, source);
    const { meta } = parseMarkdownAgent(source, file);
    writeFile(path.join(agentsDest, `${meta.name}.toml`), toml);
  }
}

function writeLocalMarketplaceIfSourcesExist(cwd) {
  const generalPlugin = path.join(cwd, 'general-plugin');
  const obsidianPlugin = path.join(cwd, 'obsidian-plugin');
  if (!fs.existsSync(generalPlugin) || !fs.existsSync(obsidianPlugin)) return;

  const marketplace = {
    name: 'vibe-coding',
    interface: { displayName: 'Vibe Coding' },
    plugins: [
      {
        name: 'general-plugin',
        source: { source: 'local', path: './general-plugin' },
        policy: { installation: 'AVAILABLE', authentication: 'ON_INSTALL' },
        category: 'Productivity',
      },
      {
        name: 'obsidian-plugin',
        source: { source: 'local', path: './obsidian-plugin' },
        policy: { installation: 'AVAILABLE', authentication: 'ON_INSTALL' },
        category: 'Productivity',
      },
    ],
  };

  writeFile(
    path.join(cwd, '.agents', 'plugins', 'marketplace.json'),
    JSON.stringify(marketplace, null, 2) + '\n'
  );
}

async function setup(cwd, { yes = false, reconfigure = false } = {}) {
  console.log('[INFO] Configuring Codex...');

  // --- ~/.codex/AGENTS.md (global) ---
  const globalCodexDir = path.join(os.homedir(), '.codex');
  fs.mkdirSync(globalCodexDir, { recursive: true });
  const globalAgentsPath = path.join(globalCodexDir, 'AGENTS.md');

  let writeGlobalAgents = true;
  if (fs.existsSync(globalAgentsPath) && !yes) {
    const { default: inquirer } = await import('inquirer');
    const { override } = await inquirer.prompt([{
      type: 'confirm',
      name: 'override',
      message: '~/.codex/AGENTS.md already exists. Override with latest template?',
      default: false,
    }]);
    writeGlobalAgents = override;
  }

  if (writeGlobalAgents) writeFile(globalAgentsPath, readTemplate('global-claude.md'));

  // --- API keys ---
  const keys = await resolveKeys([
    { name: 'GITHUB_PERSONAL_ACCESS_TOKEN', hint: 'github.com/settings/tokens' },
    { name: 'CONTEXT7_API_KEY',             hint: 'context7.com' },
    { name: 'TAVILY_API_KEY',               hint: 'tavily.com' },
  ], { yes, reconfigure });

  // --- ~/.codex/config.toml (global) ---
  const configPath = path.join(globalCodexDir, 'config.toml');
  let writeConfig = true;
  if (fs.existsSync(configPath) && !yes) {
    const { default: inquirer } = await import('inquirer');
    const { override } = await inquirer.prompt([{
      type: 'confirm',
      name: 'override',
      message: '~/.codex/config.toml already exists. Update vibe MCP sections?',
      default: true,
    }]);
    writeConfig = override;
  }

  if (writeConfig) {
    const generatedConfig = renderCodexConfig({
      githubToken: keys.GITHUB_PERSONAL_ACCESS_TOKEN || '',
      context7Key: keys.CONTEXT7_API_KEY || '',
      tavilyKey: keys.TAVILY_API_KEY || '',
    });
    const existingConfig = fs.existsSync(configPath) ? fs.readFileSync(configPath, 'utf8') : '';
    writeFile(configPath, mergeCodexConfig(existingConfig, generatedConfig));
  }

  // --- Subagents (global) ---
  writeCodexAgents(globalCodexDir);

  // --- Repo-local marketplace metadata when running from this repository ---
  writeLocalMarketplaceIfSourcesExist(cwd);

  // --- Codex plugin update/install flow ---
  exec('codex plugin marketplace add AndrewChang-cpu/vibe-coding-configuration');
  exec('codex plugin marketplace upgrade vibe-coding');
  exec('codex plugin add general-plugin@vibe-coding');
  exec('codex plugin add obsidian-plugin@vibe-coding');

  console.log('[SUCCESS] Codex configured.');
}

module.exports = { setup };
